### ISSUE TITLE
Naming convention: ControllerAction(form_id)

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#11]
Why `form_id` and not just `id`?

````
public function SaveAction($id) {
        $id += 0;
````

- `form_id` is associated with DOM ID like `<form id="someDocumentID" ...`
- `id` is associated with existing entity for the current controller/model, it's like `this` keyword

Consider the following request:

`http://osafw.com/Manage/Bookings/555`

It means that some **Controller** performs **Mange** action on **Booking** entity with **number-like ID 555** . But the **Booking** page may have several forms with **string-like DOM IDs** ("bookingForm", "smsForm", "emalForm" etc) .

**Comment by osalabs** [comment]
I've used `$form_id`  (string) in action param just because to differentiate from `$id` (integer).
But I see your point... let me think about it a bit

**Comment by osalabs** [comment]
I am leaving it as is in current fw code (i.e. $form_id as param and then `$id = $form_id+0;`) because $form_id in general case could be not integer and, for example UUID. Or `$form_id` could be some composite ID like '1234-5555' where you might extract actually 2 ids.

However, in your custom controllers it's fine to use just $id without $form_id (however `$id+=0` still recommended to prevent security issues)
