### ISSUE TITLE
Best practice: changing layout

### ISSUE THREAD

**Issue by vladsavchuk** [osalabs/osafw-php#26]
I need a custom layout for printing.

Is this the proper approach to change the default layout for Controller?
````
    public function __construct() {
        parent::__construct();
        $this->fw->page_layout = '/site/layout_print_custom.html';
    }
````

**Comment by osalabs** [comment]
Yes, if you need to change page layout for the all Controller actions - change it in `__construct()`
However you might already have all layouts in config, so instead of hardcoded string, code will look like:
```
    public function __construct() {
        parent::__construct();
        $this->fw->page_layout = $this->fw->config->PAGE_LAYOUT_PRINT;
    }
```

Another option, if you just want to change page layout for particular action - set it right in the action:
```
    public function PrintAction() {
      $ps=array(
         '_layout' ->$this->fw->config->PAGE_LAYOUT_PRINT;
      );
      ....
      return $ps;
    }
```
